spring:
  application:
    name: notification-system
server:
  port: 8081
#  servlet:
#    context-path: /notification-system
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/