version: '3.8'

services:
  db:
    image: docker.io/postgres:15.2
    container_name: notification_db
    restart: always
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notificatiodb
      - POSTGRES_USER=gtzuc
      - POSTGRES_PASSWORD=rootGtzuc
    ports:
      - "5432:5432"

volumes:
  postgres_data:
